name: TeslaRIS Deploy

on:
  workflow_dispatch:
    inputs:
      skip_tests:
        description: 'Skip running tests'
        default: false
        required: false


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Build and package with Maven
        run: mvn clean package

      - name: Echo test
        run: ls -l
