name: TeslaRIS Script runner

on:
  workflow_dispatch:
    inputs:
      script_name:
        type: choice
        description: Script
        options: 
        - reindex
        - reset_database
        - test
        required: true
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment || 'test' }}

    steps:
      - name: Run script - ${{ inputs.script_name }}.sh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          script: |
            /opt/teslaris/scripts/${{ inputs.script_name }}.sh
